---
title: Well Modeling and Batch Automation
author: "Alfonso R. Reyes"
date: "April 2019"
fontsize: 14pt
output:
  beamer_presentation:
    fig_width: 7
    fig_height: 3.5
    highlight: tango
    theme: metropolis
    includes:
      in_header: headerOG.tex
---


```{r setup-DO, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning=FALSE, 
                      message=FALSE,
                      comment = "#>"
                      )
options(digits=4)
```


# Well modeling and batch automation

## Why automating well modeling?
\fontsize{13}{15}\sf
- Modeling takes a long time
- It is laborious to calibrate and modify each model
- It is easy for ten wells
- But very hard on 25, 50, 100, 200+ wells
- And when you finish the first batch of well tests ...
- ... it comes another ...
- One production optimization cycle could take months


## How is it like now?
\fontsize{13}{15}\sf
* Models take from 3-9 months to build $$f(N)$$ 
where $N$ is the number of wells
* Models do not immediately match
* Wrong models left as-is to move on to network optimization
* Get wrong results from the optimization solver
* In the end: \newline
\fontsize{12}{14}\sf
\alert{Production Optimization is great but becomes unreliable}


## Sample multiwell table
\fullwidth{well_scanner_output_2}



# Statistical analysis
## Statistical analysis
\begin{alertblock}{}
Statistical Analysis makes a difference
\end{alertblock}  

\vspace{1.0cm}

\fontsize{13}{15}\sf
* All wells data get into a tabular format: dataframe
* Every well is a row (observation) 
* Well parameters become columns or variables
* Tables make easier to spot problems with the data
* Well scanning can be done on a directory or drive
* Well variables (columns) are selectable


## Advantages
* Matching the models gets certain
* Reliable Well Models Construction
* Issues with well tests get more manageable
* Learn to trust the data


# Batch Automation

## Current wokflow of model building
\fontsize{13}{15}\sf
\begin{alertblock}{}
  Why doesn't work most of the time
\end{alertblock}  

\vspace{1.0cm}

* You deal with one well at a time
* Cannot see the variation between wells: isolated
* Well data cannot be compared
* There is no data structure in place
* No input validation but by the software
* Model files are in binary format


## New workflow with batch automation
\fontsize{13}{15}\sf
* We deal with all wells at the same time
* Wells are scanned and read into a master dataset
* Scanning multiple wells of the same field saves time
* Dataframes are ideal for statistical analysis
* We are able to compare dozens to hundreds of wells
* Models can be saved as CSV, xls, text, JSON, anything
* You are in control of the whole process



# Network Analysis

## In the network optimizer
- Retrieve all the solver variables
- Put the variables in a dataframe
- Calculate new variables as KPIs
- Statistically compare the KPIs
- Arrange the wells by best and worst KPI
- Run additional scenarios

\vspace{2.0cm}
<!--    center text   -->
\begin{center}\textcolor{orange}{KPI: Key Performance Indicators}\end{center}

## Gas Lift KPIs
\fontsize{11}{13}\sf
\placefig{3.5}{2.0}{width=6.5cm, height=6.5cm}{gl_kpis}





## Network table
\fullwidth{network_kpi_gl_variables}

## Network Analysis
\fontsize{13}{15}\sf
* Putting all well models together and connected
* Run well VLPs and export them 
* Automating the process: standalone well + network
* Building a reliable network
* Build several templates for scenario building
* Leave the computer running the network optimization



# Benefits of well batch automation

## Benefits of the approach
* Considerable time savings: months to weeks
* Identify hidden oil
* Keep production optimized
* Detect failures
* Reallocate water and gas injection
* Identify field needs
* Hands off building of optimization scenarios

## At company level
\fontsize{13}{15}\sf
* Scepticism at first
* Increase of oil production from 3 to 25%
* Reduced time for the well model process to days
* Reduced time for network modeling to weeks instead of months
* Petroleum Engineers saw the benefits of using statistics
* A new data culture was born
* Operators start trusting the data


# Tools for batch automation
## Tools for batch automation
* Prosper
* GAP
* MBAL
* OpenServer
* Python noteboks: Jupyter, or GUI
* R scripts
* Or its equivalent PipeSim and friends ...

## Packages coming soon
* rOpenServer
* rProsper
* rGap
* rMbal
* rNodal

## Code
\fullwidth{well_scanner_script}



